global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: '8424256561:AAHGDKMQRXHnn-WLlERdrOIoSyK6G1oOcFE'
        chat_id: 6871748022
        parse_mode: 'HTML'
        message: |
          ðŸš¨ <b>{{ .Status | toUpper }}</b>
          {{ range .Alerts }}
          <b>{{ .Labels.alertname }}</b>
          {{ .Annotations.description }}
          {{ end }}
